app: annemarie
ssh_url: annemarie@deploy.eu2.frbit.com
git_remote: annemarie/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
