isPublic: true
name: 'Public Schema'
scope:
  - 'sections.c6f2bbff-6ff0-4801-9dcf-338168643bec:edit' # Pages
  - 'sections.c6f2bbff-6ff0-4801-9dcf-338168643bec:create' # Pages
  - 'sections.c6f2bbff-6ff0-4801-9dcf-338168643bec:save' # Pages
  - 'sections.c6f2bbff-6ff0-4801-9dcf-338168643bec:delete' # Pages
