color: null
fieldLayouts:
  94fcf334-08c4-494b-8bf1-bbb1e2f1e86e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-18T16:06:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d6123dd2-a96c-45d4-8def-2604c022bcd6 # Hero heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feb53727-4030-460c-b14f-23a55210f50b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T13:50:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 64683d3b-41d1-400d-9550-96e6bb09ad76 # Hero heading two
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5ba58e6-c01d-4fa2-9d11-8b5706bbbe65
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T16:06:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6a06764d-08c8-4133-a298-ff2e68dfb3d3 # Hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34706560-780f-466d-ba2b-0f893dd9032f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T13:50:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 557631a2-a862-4ecd-a8f0-b65cf1c26c96 # Hero desc
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d79b20b-d2df-44d8-a673-6d137305f428
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b06350fd-a615-49fd-ae88-1e0c4afdc783
        userCondition: null
handle: hero
hasTitleField: false
icon: image-landscape
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
