color: null
fieldLayouts:
  31a5c4da-d42e-42f9-8438-7f3981a78b22:
    cardView:
      - section
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-22T16:53:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc2e964d-403a-447f-988b-b6fd85294ad4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-22T16:58:24+00:00'
            elementCondition: null
            fieldUid: 83726e8b-7ebd-4e41-a5fc-cb64d6475f84 # Page name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1216ab2d-dc37-4e02-b2d6-9595a42cb3a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-23T15:11:06+00:00'
            elementCondition: null
            fieldUid: 5765e8f2-59c3-4d6c-9d78-01092c8f47c8 # Matric test
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16332096-7fe1-4a2a-9223-577fe9d7ef88
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5762b741-767f-458c-85dd-cb6e16981a1f
        userCondition: null
handle: pagetitle
hasTitleField: true
icon: heading
name: pageTitle
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
