import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';


// inject custom font during SSR to avoid layout shift
const gilroy = localFont({
  src: [
    {
      path: '/fonts/gilroy-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/gilroy-heavy-webfont.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-gilroy',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gilroy.variable}>
        {children}
      </body>
    </html>
  );
}
