defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5851d863-cd85-48c4-84b6-1950ab414d34
handle: home
maxAuthors: 1
name: home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b3c8a8f4-2b91-4313-907b-0a2c01eb543f: # Freelance Front-end Developer
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
