defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1bb3dd4d-d0f0-4e6d-989b-15b3686e5c46 # Components
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b3c8a8f4-2b91-4313-907b-0a2c01eb543f: # Freelance Front-end Developer
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'pages/{slug}'
structure:
  maxLevels: null
  uid: 9330a585-4819-4168-ac00-0098ba3db09f
type: structure
