columnSuffix: null
handle: pageName
instructions: null
name: 'Page name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Enter the page title'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
