altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  db1048d6-8008-4b59-b90b-6452896fdd4e:
    cardView:
      - filename
      - id
      - height
      - width
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-23T15:38:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bb5f8e32-f71f-454a-8817-5dc93e99fe66
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2a4c9fdd-f9ff-404c-94d8-527fe6c54e7c
        userCondition: null
fs: images
handle: featureImages
name: 'Feature Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
